### ISSUE TITLE
没有看视频翻倍了呀

### ISSUE THREAD

**Issue by xushen1994** [TNanko/leam#34]
![企业微信截图_16098203005094](https://user-images.githubusercontent.com/50359013/103605953-2d3ecb00-4f50-11eb-8c80-830f6a31f3b8.png)
【宝箱奖励翻倍】不在了

**Comment by TNanko** [comment]
> ![企业微信截图_16098203005094](https://user-images.githubusercontent.com/50359013/103605953-2d3ecb00-4f50-11eb-8c80-830f6a31f3b8.png)
> 【宝箱奖励翻倍】不在了

有的，它会在下一个 10 分钟开翻倍宝箱，不过好像会漏掉几个翻倍宝箱，最新版本的我已经修复这个问题了，但是还没 git push ，我再看看有没有其他 bug ，晚一点上传代码

**Comment by xushen1994** [comment]
> > ![企业微信截图_16098203005094](https://user-images.githubusercontent.com/50359013/103605953-2d3ecb00-4f50-11eb-8c80-830f6a31f3b8.png)
> > 【宝箱奖励翻倍】不在了
> 
> 有的，它会在下一个10分钟开翻倍宝箱，你可以往上翻一下上一次跑的日志，不过好像会漏掉几个翻倍宝箱，最新版本的我已经修复这个问题了，但是还没git push，我再看看有没有其他bug，晚一点上传代码

好的，谢谢大佬，大佬辛苦了。

**Comment by hengwuming** [comment]
> > ![企业微信截图_16098203005094](https://user-images.githubusercontent.com/50359013/103605953-2d3ecb00-4f50-11eb-8c80-830f6a31f3b8.png)
> > 【宝箱奖励翻倍】不在了
> 
> 有的，它会在下一个 10 分钟开翻倍宝箱，你可以往上翻一下上一次跑的日志，不过好像会漏掉几个翻倍宝箱，最新版本的我已经修复这个问题了，但是还没 git push ，我再看看有没有其他 bug ，晚一点上传代码

大佬，解决了吗，我下载最新版本跑的时候发现还是不能看视频翻倍

**Comment by TNanko** [comment]
> > > ![企业微信截图_16098203005094](https://user-images.githubusercontent.com/50359013/103605953-2d3ecb00-4f50-11eb-8c80-830f6a31f3b8.png)
> > > 【宝箱奖励翻倍】不在了
> > 
> > 
> > 有的，它会在下一个 10 分钟开翻倍宝箱，你可以往上翻一下上一次跑的日志，不过好像会漏掉几个翻倍宝箱，最新版本的我已经修复这个问题了，但是还没 git push ，我再看看有没有其他 bug ，晚一点上传代码
> 
> 大佬，解决了吗，我下载最新版本跑的时候发现还是不能看视频翻倍

去看日志，把日志完整看一遍，然后再去你手机里看收益

**Comment by xushen1994** [comment]
> > > > ![企业微信截图_16098203005094](https://user-images.githubusercontent.com/50359013/103605953-2d3ecb00-4f50-11eb-8c80-830f6a31f3b8.png)
> > > > 【宝箱奖励翻倍】不在了
> > > 
> > > 
> > > 有的，它会在下一个 10 分钟开翻倍宝箱，你可以往上翻一下上一次跑的日志，不过好像会漏掉几个翻倍宝箱，最新版本的我已经修复这个问题了，但是还没 git push ，我再看看有没有其他 bug ，晚一点上传代码
> > 
> > 
> > 大佬，解决了吗，我下载最新版本跑的时候发现还是不能看视频翻倍
> 
> 去看日志，把日志完整看一遍，然后再去你手机里看收益

![微信图片_20210106190252](https://user-images.githubusercontent.com/50359013/103761601-e2a57780-5051-11eb-9891-9088298f13ef.jpg)
真的没有大佬，我是在github actions里面运行的，从昨天到现在一直是没得翻倍。

**Comment by TNanko** [comment]
1.代码更新到最新版本
2.github action 的 cron 本来就是不准的，最新版本要求 cron 准确，能跑满 72 个箱子

> > > > > ![企业微信截图_16098203005094](https://user-images.githubusercontent.com/50359013/103605953-2d3ecb00-4f50-11eb-8c80-830f6a31f3b8.png)
> > > > > 【宝箱奖励翻倍】不在了
> > > > 
> > > > 
> > > > 有的，它会在下一个 10 分钟开翻倍宝箱，你可以往上翻一下上一次跑的日志，不过好像会漏掉几个翻倍宝箱，最新版本的我已经修复这个问题了，但是还没 git push ，我再看看有没有其他 bug ，晚一点上传代码
> > > 
> > > 
> > > 大佬，解决了吗，我下载最新版本跑的时候发现还是不能看视频翻倍
> > 
> > 
> > 去看日志，把日志完整看一遍，然后再去你手机里看收益
> 
> ![微信图片_20210106190252](https://user-images.githubusercontent.com/50359013/103761601-e2a57780-5051-11eb-9891-9088298f13ef.jpg)
> 真的没有大佬，我是在github actions里面运行的，从昨天到现在一直是没得翻倍。

**Comment by xushen1994** [comment]
emmmm，我拉本地试下 cron 默认10分钟一次就可以哇

**Comment by TNanko** [comment]
对，建议用 vps 或者 nas 等等

**Comment by hengwuming** [comment]
> 对，建议用 vps 或者 nas 等等

我是在windows下定时任务7分钟一跑的，我在收益里面确实是没有翻倍，这个该怎么解决。

**Comment by TNanko** [comment]
设置为10分钟，如果帐号多，建议分开跑，并发对网络要求比较高

**Comment by hengwuming** [comment]
> 设置为10分钟，如果帐号多，建议分开跑，并发对网络要求比较高

5个账号1m宽带并发能接受的了吗

**Comment by hengwuming** [comment]
我刚刚拿一个号测试了下，在有宝箱的情况下，开了宝箱但是不执行翻倍，日志没有输出，收益详情里也没有输出
================【企鹅读书】2021-01-06 11:35:15/2021-01-06 19:35:15 ================
☆【企鹅读书】2021-01-06 19:35:15 ☆

【用户昵称】xxx
【金币余额】剩余29944金币，可提现2元
【今日收益】8724金币，约0.87元
【本周阅读】18小时2分钟
【今日阅读】7小时56分钟
【立即阅读《我真没想重生啊》】100金币，已完成
【阅读任务】600金币，已完成
【明日打卡】588金币，去查看
【看视频领金币】500金币，已完成(5/5)
【邀请任务】1月第2期(1.4-6)，已邀0人，再邀请1人可获2000金币
【粉丝分成】已有0个粉丝，今日获得分成0金币
【宝箱任务】已开55个宝箱，下一个宝箱看视频开宝箱
【开启第56个宝箱】获得77金币
【阅读时长】成功增加4分19秒的阅读时长
【数据跟踪】跟踪成功！
【自动提现】未启用该功能
🕛耗时：2.59秒
如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~

**Comment by TNanko** [comment]
这个是第一个10分钟开正常宝箱，第二个十分开翻倍宝箱，我这边好像翻倍宝箱可能会漏掉几个（可能是网络原因）

**Comment by hengwuming** [comment]
> 这个是第一个10分钟开正常宝箱，下一个十10分钟开翻倍宝箱，我这边好像翻倍宝箱可能会漏掉几个（可能是网络原因）

那我我先挂着10分钟的试试。

**Comment by xushen1994** [comment]
测试了，定时任务10分钟一次确实可以翻倍，不翻倍的概率还是挺大，差不多50%。阿里云服务器centos系统上面测试的。

**Comment by xushen1994** [comment]
一个号不翻倍集体账号都不会翻倍。

**Comment by TNanko** [comment]
> 测试了，定时任务10分钟一次确实可以翻倍，不翻倍的概率还是挺大，差不多50%。阿里云服务器centos系统上面测试的。

几个账号啊，如果在机器性能足够的话是没有问题的，估计你机器的带宽低吧，你可以在丢进 进程池 这边延迟2-5秒试试

**Comment by TNanko** [comment]
> 一个号不翻倍集体账号都不会翻倍。

那个不可能，这个最多是概率事件

**Comment by xushen1994** [comment]
> > 测试了，定时任务10分钟一次确实可以翻倍，不翻倍的概率还是挺大，差不多50%。阿里云服务器centos系统上面测试的。
> 
> 几个账号啊，如果在机器性能足够的话是没有问题的，估计你机器的带宽低吧，你可以在丢进 进程池 这边延迟2-5秒试试

好的大佬，我试哈，我的服务器是阿里云1mb带宽的，可能会有影响。

**Comment by xushen1994** [comment]
4个账号

**Comment by TNanko** [comment]
> 测试了，定时任务10分钟一次确实可以翻倍，不翻倍的概率还是挺大，差不多50%。阿里云服务器centos系统上面测试的。

概率不会这么大，因为它是有具体的时间来控制的，你不是从凌晨开始运行的，就有时间差了

**Comment by hengwuming** [comment]
> > 一个号不翻倍集体账号都不会翻倍。
> 
> 那个不可能，这个最多是概率事件，每个账号之间是单独运行的，唯一有联系的就是共享 vps 资源

emm，我试了好几次，就是不会翻倍，但是一放到旧版本里跑就立马翻倍。

**Comment by TNanko** [comment]
> > > 一个号不翻倍集体账号都不会翻倍。
> > 
> > 
> > 那个不可能，这个最多是概率事件，每个账号之间是单独运行的，唯一有联系的就是共享 vps 资源
> 
> emm，我试了好几次，就是不会翻倍，但是一放到旧版本里跑就立马翻倍。

有运行日志吗

**Comment by hengwuming** [comment]
> > > > [一个号不翻倍集体账号都不会翻倍。](url)
> > > 
> > > 
> > > 那个不可能，这个最多是概率事件，每个账号之间是单独运行的，唯一有联系的就是共享 vps 资源
> > 
> > 
> > emm，我试了好几次，就是不会翻倍，但是一放到旧版本里跑就立马翻倍。
> 
> 有没有报错和有运行日志吗

没有报错，有运行日志

================【企鹅读书】2021-01-06 11:35:15/2021-01-06 19:35:15 ================
☆【企鹅读书】2021-01-06 19:35:15 ☆

【用户昵称】战天使
【金币余额】剩余29944金币，可提现2元
【今日收益】8724金币，约0.87元
【本周阅读】18小时2分钟
【今日阅读】7小时56分钟
【立即阅读《我真没想重生啊》】100金币，已完成
【阅读任务】600金币，已完成
【明日打卡】588金币，去查看
【看视频领金币】500金币，已完成(5/5)
【邀请任务】1月第2期(1.4-6)，已邀0人，再邀请1人可获2000金币
【粉丝分成】已有0个粉丝，今日获得分成0金币
【宝箱任务】已开55个宝箱，下一个宝箱看视频开宝箱
【开启第56个宝箱】获得77金币
【阅读时长】成功增加4分19秒的阅读时长
【数据跟踪】跟踪成功！
【自动提现】未启用该功能
🕛耗时：2.59秒
如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
2021-01-06  19:50:09 Wed TNanko's Scripts INFO

================【企鹅读书】2021-01-06 11:50:07/2021-01-06 19:50:07 ================
☆【企鹅读书】2021-01-06 19:50:07 ☆

【用户昵称】战天使
【金币余额】剩余30098金币，可提现3元
【今日收益】8878金币，约0.89元
【本周阅读】18小时7分钟
【今日阅读】8小时1分钟
【立即阅读《我真没想重生啊》】100金币，已完成
【阅读任务】600金币，已完成
【明日打卡】588金币，去查看
【看视频领金币】500金币，已完成(5/5)
【邀请任务】1月第2期(1.4-6)，已邀0人，再邀请1人可获2000金币
【粉丝分成】已有0个粉丝，今日获得分成0金币
【宝箱任务】已开56个宝箱，下一个宝箱5分钟后领取
【阅读时长】成功增加4分58秒的阅读时长
【数据跟踪】跟踪成功！
【自动提现】未启用该功能
🕛耗时：2.65秒
如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
2021-01-06  20:00:07 Wed TNanko's Scripts INFO

================【企鹅读书】2021-01-06 12:00:04/2021-01-06 20:00:04 ================
☆【企鹅读书】2021-01-06 20:00:04 ☆

【用户昵称】战天使
【金币余额】剩余30098金币，可提现3元
【今日收益】8878金币，约0.89元
【本周阅读】18小时12分钟
【今日阅读】8小时6分钟
【立即阅读《我真没想重生啊》】100金币，已完成
【阅读任务】600金币，已完成
【明日打卡】588金币，去查看
【看视频领金币】500金币，已完成(5/5)
【邀请任务】1月第2期(1.4-6)，已邀0人，再邀请1人可获2000金币
【粉丝分成】已有0个粉丝，今日获得分成0金币
【宝箱任务】已开56个宝箱，下一个宝箱看视频开宝箱
【开启第57个宝箱】获得70金币
【阅读时长】成功增加4分8秒的阅读时长
【数据跟踪】跟踪成功！
【自动提现】未启用该功能
🕛耗时：2.53秒
如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
2021-01-06  20:10:06 Wed TNanko's Scripts INFO

================【企鹅读书】2021-01-06 12:10:04/2021-01-06 20:10:04 ================
☆【企鹅读书】2021-01-06 20:10:04 ☆

【用户昵称】战天使
【金币余额】剩余30168金币，可提现3元
【今日收益】8948金币，约0.89元
【本周阅读】18小时16分钟
【今日阅读】8小时10分钟
【立即阅读《我真没想重生啊》】100金币，已完成
【阅读任务】600金币，已完成
【明日打卡】588金币，去查看
【看视频领金币】500金币，已完成(5/5)
【邀请任务】1月第2期(1.4-6)，已邀0人，再邀请1人可获2000金币
【粉丝分成】已有0个粉丝，今日获得分成0金币
【宝箱任务】已开57个宝箱，下一个宝箱10分钟后领取
【阅读时长】成功增加5分48秒的阅读时长
【数据跟踪】跟踪成功！
【自动提现】未启用该功能
🕛耗时：2.30秒
如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
2021-01-06  20:20:07 Wed TNanko's Scripts INFO

================【企鹅读书】2021-01-06 12:20:05/2021-01-06 20:20:05 ================
☆【企鹅读书】2021-01-06 20:20:05 ☆

【用户昵称】战天使
【金币余额】剩余30168金币，可提现3元
【今日收益】8948金币，约0.89元
【本周阅读】18小时22分钟
【今日阅读】8小时16分钟
【立即阅读《我真没想重生啊》】100金币，已完成
【阅读任务】600金币，已完成
【明日打卡】588金币，去查看
【看视频领金币】500金币，已完成(5/5)
【邀请任务】1月第2期(1.4-6)，已邀0人，再邀请1人可获2000金币
【粉丝分成】已有0个粉丝，今日获得分成0金币
【宝箱任务】已开57个宝箱，下一个宝箱0分钟后领取
【开启第58个宝箱】获得69金币
【阅读时长】成功增加4分12秒的阅读时长
【数据跟踪】跟踪成功！
【自动提现】未启用该功能
🕛耗时：2.53秒
如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~

**Comment by TNanko** [comment]
手动运行，日志里面不会出现错误信息。如果还是这样，那我就不清楚了，大部分人使用是有翻倍的

> > > > > [一个号不翻倍集体账号都不会翻倍。](url)
> > > > 
> > > > 
> > > > 那个不可能，这个最多是概率事件，每个账号之间是单独运行的，唯一有联系的就是共享 vps 资源
> > > 
> > > 
> > > emm，我试了好几次，就是不会翻倍，但是一放到旧版本里跑就立马翻倍。
> > 
> > 
> > 有没有报错和有运行日志吗
> 
> 没有报错，有运行日志
> 
> ================【企鹅读书】2021-01-06 11:35:15/2021-01-06 19:35:15 ================
> ☆【企鹅读书】2021-01-06 19:35:15 ☆
> 
> 【用户昵称】战天使
> 【金币余额】剩余29944金币，可提现2元
> 【今日收益】8724金币，约0.87元
> 【本周阅读】18小时2分钟
> 【今日阅读】7小时56分钟
> 【立即阅读《我真没想重生啊》】100金币，已完成
> 【阅读任务】600金币，已完成
> 【明日打卡】588金币，去查看
> 【看视频领金币】500金币，已完成(5/5)
> 【邀请任务】1月第2期(1.4-6)，已邀0人，再邀请1人可获2000金币
> 【粉丝分成】已有0个粉丝，今日获得分成0金币
> 【宝箱任务】已开55个宝箱，下一个宝箱看视频开宝箱
> 【开启第56个宝箱】获得77金币
> 【阅读时长】成功增加4分19秒的阅读时长
> 【数据跟踪】跟踪成功！
> 【自动提现】未启用该功能
> 🕛耗时：2.59秒
> 如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
> 2021-01-06 19:50:09 Wed TNanko's Scripts INFO
> 
> ================【企鹅读书】2021-01-06 11:50:07/2021-01-06 19:50:07 ================
> ☆【企鹅读书】2021-01-06 19:50:07 ☆
> 
> 【用户昵称】战天使
> 【金币余额】剩余30098金币，可提现3元
> 【今日收益】8878金币，约0.89元
> 【本周阅读】18小时7分钟
> 【今日阅读】8小时1分钟
> 【立即阅读《我真没想重生啊》】100金币，已完成
> 【阅读任务】600金币，已完成
> 【明日打卡】588金币，去查看
> 【看视频领金币】500金币，已完成(5/5)
> 【邀请任务】1月第2期(1.4-6)，已邀0人，再邀请1人可获2000金币
> 【粉丝分成】已有0个粉丝，今日获得分成0金币
> 【宝箱任务】已开56个宝箱，下一个宝箱5分钟后领取
> 【阅读时长】成功增加4分58秒的阅读时长
> 【数据跟踪】跟踪成功！
> 【自动提现】未启用该功能
> 🕛耗时：2.65秒
> 如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
> 2021-01-06 20:00:07 Wed TNanko's Scripts INFO
> 
> ================【企鹅读书】2021-01-06 12:00:04/2021-01-06 20:00:04 ================
> ☆【企鹅读书】2021-01-06 20:00:04 ☆
> 
> 【用户昵称】战天使
> 【金币余额】剩余30098金币，可提现3元
> 【今日收益】8878金币，约0.89元
> 【本周阅读】18小时12分钟
> 【今日阅读】8小时6分钟
> 【立即阅读《我真没想重生啊》】100金币，已完成
> 【阅读任务】600金币，已完成
> 【明日打卡】588金币，去查看
> 【看视频领金币】500金币，已完成(5/5)
> 【邀请任务】1月第2期(1.4-6)，已邀0人，再邀请1人可获2000金币
> 【粉丝分成】已有0个粉丝，今日获得分成0金币
> 【宝箱任务】已开56个宝箱，下一个宝箱看视频开宝箱
> 【开启第57个宝箱】获得70金币
> 【阅读时长】成功增加4分8秒的阅读时长
> 【数据跟踪】跟踪成功！
> 【自动提现】未启用该功能
> 🕛耗时：2.53秒
> 如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
> 2021-01-06 20:10:06 Wed TNanko's Scripts INFO
> 
> ================【企鹅读书】2021-01-06 12:10:04/2021-01-06 20:10:04 ================
> ☆【企鹅读书】2021-01-06 20:10:04 ☆
> 
> 【用户昵称】战天使
> 【金币余额】剩余30168金币，可提现3元
> 【今日收益】8948金币，约0.89元
> 【本周阅读】18小时16分钟
> 【今日阅读】8小时10分钟
> 【立即阅读《我真没想重生啊》】100金币，已完成
> 【阅读任务】600金币，已完成
> 【明日打卡】588金币，去查看
> 【看视频领金币】500金币，已完成(5/5)
> 【邀请任务】1月第2期(1.4-6)，已邀0人，再邀请1人可获2000金币
> 【粉丝分成】已有0个粉丝，今日获得分成0金币
> 【宝箱任务】已开57个宝箱，下一个宝箱10分钟后领取
> 【阅读时长】成功增加5分48秒的阅读时长
> 【数据跟踪】跟踪成功！
> 【自动提现】未启用该功能
> 🕛耗时：2.30秒
> 如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
> 2021-01-06 20:20:07 Wed TNanko's Scripts INFO
> 
> ================【企鹅读书】2021-01-06 12:20:05/2021-01-06 20:20:05 ================
> ☆【企鹅读书】2021-01-06 20:20:05 ☆
> 
> 【用户昵称】战天使
> 【金币余额】剩余30168金币，可提现3元
> 【今日收益】8948金币，约0.89元
> 【本周阅读】18小时22分钟
> 【今日阅读】8小时16分钟
> 【立即阅读《我真没想重生啊》】100金币，已完成
> 【阅读任务】600金币，已完成
> 【明日打卡】588金币，去查看
> 【看视频领金币】500金币，已完成(5/5)
> 【邀请任务】1月第2期(1.4-6)，已邀0人，再邀请1人可获2000金币
> 【粉丝分成】已有0个粉丝，今日获得分成0金币
> 【宝箱任务】已开57个宝箱，下一个宝箱0分钟后领取
> 【开启第58个宝箱】获得69金币
> 【阅读时长】成功增加4分12秒的阅读时长
> 【数据跟踪】跟踪成功！
> 【自动提现】未启用该功能
> 🕛耗时：2.53秒
> 如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~

**Comment by TNanko** [comment]
> 一个号不翻倍集体账号都不会翻倍。

我看到你说的那个问题了，晚点我再看看

**Comment by hengwuming** [comment]
手动和自动都不会报错，那我继续用旧版本吧。

**Comment by TNanko** [comment]
已尝试修复翻倍宝箱问题

**Comment by xushen1994** [comment]
> 已尝试修复翻倍宝箱问题

大佬辛苦了(≧∇≦)/
