### ISSUE TITLE
cron 不管怎么设置  action 一个小时就运行2次，通知也有问题 ，没收到过。

### ISSUE THREAD

**Issue by kalagxw** [TNanko/leam#38]
cron 不管怎么设置  action 一个小时就运行2次，qqreader通知也有问题 ，没收到过，请问是那个时间段通知

**Comment by TNanko** [comment]
> cron 不管怎么设置 action 一个小时就运行2次，qqreader通知也有问题 ，没收到过，请问是那个时间段通知

github action 的延迟很大，薅羊毛就别用它了，每天签签到到时可以
